# Generated by Django 3.2.11 on 2022-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_changed_my_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Success_Storie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stories', models.TextField(max_length=500)),
            ],
        ),
    ]
