# Generated by Django 3.2.11 on 2022-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_success_storie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=100)),
                ('identification_code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('artiste_picture', models.FileField(upload_to='artiste_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=100)),
                ('identification_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('audio_file', models.FileField(upload_to='audio')),
                ('cover_picture', models.FileField(upload_to='cover_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=100)),
                ('identification_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('video_file', models.FileField(upload_to='video')),
            ],
        ),
        migrations.DeleteModel(
            name='All_Course',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Popular_Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Success_Storie',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='User_Course',
        ),
    ]
